### ISSUE TITLE
18.9 leia 115播放器点不开任何文件夹

### ISSUE THREAD

**Issue by 815169876** [feelfar/115-for-kodi#11]
- NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                            Error Type: <type 'exceptions.ImportError'>
                                            Error Contents: No module named lib.six
                                            Traceback (most recent call last):
                                              File "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/plugin.video.115/default.py", line 21, in <module>
                                                import comm
                                              File "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/plugin.video.115/comm.py", line 32, in <module>
                                                from commfunc import get_storage
                                              File "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/plugin.video.115/lib/commfunc.py", line 22, in <module>
                                                import lib.six as six
                                            ImportError: No module named lib.six
                                            -->End of Python script error report<--
2021-03-18 10:12:48.041 T:15286   ERROR: GetDirectory - Error getting plugin://plugin.video.115/
2021-03-18 10:12:48.054 T:15202   ERROR: CGUIMediaWindow::GetDirectory(plugin://plugin.video.115/) failed
2021-03-18 10:12:48.528 T:15238   ERROR: script.kodi.android.update-1.1.7-deleteLast Failed! 'Service' object has no attribute 'lastPath' ,Traceback (most recent call last):
                                              File "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/script.kodi.android.update/service.py", line 51, in deleteLast
                                                xbmcvfs.delete(self.lastPath)
                                            AttributeError: 'Service' object has no attribute 'lastPath'
2021-03-18 10:12:48.890 T:15239   ERROR: XBMCLocalProxy Starts - 0.0.0.0:6227
2021-03-18 10:12:53.988 T:15202   ERROR: Control 50 in window 10025 has been asked to focus, but it can't
2021-03-18 10:12:54.889 T:15344   ERROR: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                             - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                            Error Type: <type 'exceptions.ImportError'>
                                            Error Contents: No module named lib.six
                                            Traceback (most recent call last):
                                              File "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/plugin.video.115/default.py", line 21, in <module>
                                                import comm
                                              File "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/plugin.video.115/comm.py", line 32, in <module>
                                                from commfunc import get_storage
                                              File "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/plugin.video.115/lib/commfunc.py", line 22, in <module>
                                                import lib.six as six
                                            ImportError: No module named lib.six
                                            -->End of Python script error report<--
2021-03-18 10:12:54.918 T:15343   ERROR: GetDirectory - Error getting plugin://plugin.video.115/
2021-03-18 10:12:54.929 T:15202   ERROR: CGUIMediaWindow::GetDirectory(plugin://plugin.video.115/) failed
2021-03-18 10:14:54.523 T:15211  NOTICE: Trying to open: samplerate: 44100, channelMask: 12, encoding: 4
2021-03-18 10:14:54.533 T:15211  NOTICE: CAESinkAUDIOTRACK::Initializing with: m_sampleRate: 44100 format: AE_FMT_FLOAT (AE) method: PCM stream-type: PCM-STREAM min_buffer_size: 22688 m_frames: 1418 m_frameSize: 8 channels: 2
2021-03-18 10:15:02.115 T:15202   ERROR: Misplaced !
2021-03-18 10:15:02.115 T:15202   ERROR: Error parsing boolean expression string.endswith(listitem.label,!)
2021-03-18 10:15:21.362 T:15502  NOTICE: ADDON:

**Comment by feelfar** [comment]
你的运行环境、kodi版本是？

**Comment by 815169876** [comment]
> 你的运行环境、kodi版本是？

2021-03-18 10:12:31.938 T:15202  NOTICE: Starting Kodi (18.9 (18.9.0) Git:20201023-0655c2c718). Platform: Android ARM 64-bit
2021-03-18 10:12:31.938 T:15202  NOTICE: Using Release Kodi x64 build
2021-03-18 10:12:31.938 T:15202  NOTICE: Kodi compiled 2020-10-23 by Clang 7.0.2 (https://android.googlesource.com/toolchain/clang 003100370607242ddd5815e4a043907ea9004281) (https://android.googlesource.com/toolchain/llvm 1d739ffb0366421d383e04ff80ec2ee591315116) for Android ARM 64-bit API level 21 (API level 21)
2021-03-18 10:12:31.938 T:15202  NOTICE: Running on NVIDIA SHIELD Android TV with Android 9.0.0 API level 28, kernel: Linux ARM 64-bit version 4.9.140-tegra-g5eb7ca7547d4
2021-03-18 10:12:31.938 T:15202  NOTICE: FFmpeg version/source: 4.0.4-Kodi

**Comment by feelfar** [comment]
还看不出原因，你试下将commfunc.py文件从lib目录移出到插件目录下，看能不能修复
